### ISSUE TITLE
Q3 question

### ISSUE THREAD

**Issue by JeGa** [teed/ml_homework#1]
Is there a proof for the answer of Q3 ([line](https://github.com/teed/ml_homework/blob/07c871e346d8243ad9d00cc3e4602d19c82e3c11/preparation_questions/09_preparation_questions_draft.txt#L8))?

Thanks

**Comment by TomLadek** [comment]
Try it and you'll see!

**Comment by JeGa** [comment]
Thanks, i will try it someday,
